In [1]:
import numpy
numpy.__version__

'1.14.0'

In [68]:
import numpy as np

In [3]:
np?

In [4]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array.array?

In [6]:
# 정수 배열
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [8]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
# 리스트를 중첩하면 다차원 배열이 됨
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# 1로 채운 3x5 부동 소수점 배열 만들기
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# 3.14로 채운 3x5 배열 만들기
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씩 더해 20까지 채움
# (내장 함수인 range()와 유사함)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# 균등하게 분포된 3x3 배열 만들기
# 0과 1 사이의 난수로 채움
np.random.random((3, 3))

array([[0.00272289, 0.49191046, 0.51667236],
       [0.56393932, 0.33651208, 0.50897536],
       [0.04644057, 0.84110545, 0.75339911]])

In [16]:
# 정규 분포(평균=0, 표준 편차=1)의 난수로 채운 3x3 배열 만들기
np.random.normal(0, 1, (3, 3))

array([[ 0.91029325,  0.98684174, -0.03004585],
       [-0.39706355,  1.4122174 , -1.55663783],
       [ 0.87669606,  0.08451034,  0.24746258]])

In [43]:
# [0,10) 구간의 임의의 정수로 채운 3x3 배열 만들기
np.random.randint(0, 10, (3, 3))

array([[9, 6, 7],
       [4, 6, 5],
       [9, 1, 0]])

In [45]:
# 3x3 단위 행렬 만들기
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(3)

array([1., 1., 1.])

In [47]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [48]:
np.zeros(10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [53]:
np.typecodes

{'All': '?bhilqpBHILQPefdgFDGSUVOMm',
 'AllFloat': 'efdgFDG',
 'AllInteger': 'bBhHiIlLqQpP',
 'Character': 'c',
 'Complex': 'FDG',
 'Datetime': 'Mm',
 'Float': 'efdg',
 'Integer': 'bhilqp',
 'UnsignedInteger': 'BHILQP'}

In [56]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)  # 1차원 배열
x2 = np.random.randint(10, size=(3,4))  # 2차원 배열
x3 = np.random.randint(10, size=(3,4,5))  # 3차원 배열

In [58]:
print("x1\n", x1)
print("x2\n", x2)
print("x3\n", x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "bytes")

x1
 [5 0 3 3 7 9]
x2
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int32
x3 itemsize:  4 bytes
x3 nbytes:  240 bytes


In [59]:
x1[0] = 3.14159  # 이 값의 소수점 이하는 잘릴 것이다!
x1

array([3, 0, 3, 3, 7, 9])

In [60]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x[:5]

array([0, 1, 2, 3, 4])

In [62]:
x[5:]

array([5, 6, 7, 8, 9])

In [63]:
x[4:7]

array([4, 5, 6])

In [64]:
x[::2]

array([0, 2, 4, 6, 8])

In [65]:
x[1::2]

array([1, 3, 5, 7, 9])

In [66]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [67]:
x[5::-2]

array([5, 3, 1])

In [69]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [70]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [71]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [72]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [73]:
print(x2[:, 0])
print(x2[0, :])

[3 7 1]
[3 5 2 4]


In [74]:
x2[0]

array([3, 5, 2, 4])

In [75]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [76]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[3 5]
 [7 6]]


In [77]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [78]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [79]:
x2_sub_copy = x2[:2, :2].copy()
print(x2)
print(x2_sub)
print(x2_sub_copy)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[99  5]
 [ 7  6]]


In [81]:
x2_sub_copy[0, 0] = 44
print(x2)
print(x2_sub)
print(x2_sub_copy)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[44  5]
 [ 7  6]]


In [82]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
x  = np.array([1, 2, 3])
# reshape을 이용한 행 백터
x.reshape((1,3))

array([[1, 2, 3]])

In [84]:
# newaxis를 이용한 행 벡터
x[np.newaxis, :]

array([[1, 2, 3]])

In [85]:
# reshape을 이용한 열 벡터
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [86]:
# newaxis를 이용한 열 벡터
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [88]:
x

array([1, 2, 3])

In [89]:
x.reshape(1, -1)

array([[1, 2, 3]])

In [90]:
t = np.array([[i, i] for i in range(10)])
t

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [95]:
t1 = t.reshape(1, -1)
t1

array([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]])

In [97]:
t1.reshape(-1, 2)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [99]:
sample = np.array([123, 456])
print(sample)
sample.reshape(1, -1)

[123 456]


array([[123, 456]])