In [2]:
import numpy
a = numpy.arange(12)
print(type(a), a)

<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
print(a.shape)
a.shape = 3, 4
print(a)
print(a[2])
a[2, 1]

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]


9

In [5]:
print(a[:, 1])
a.transpose()

[1 5 9]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [11]:
from random import random

fp = open('floats-10M-lines.txt', 'w')
for i in (random() for i in range(10**7)):
    fp.write(str(i) + '\n')
fp.close()


In [12]:
floats = numpy.loadtxt('floats-10M-lines.txt')
floats[-3:]

array([0.24927783, 0.07516683, 0.25363684])

In [13]:
floats *= .5
floats[-3:]

array([0.12463891, 0.03758342, 0.12681842])

In [14]:
from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0

0.011786257613164392

In [15]:
numpy.save('floats-10M', floats)
floats2 = numpy.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

memmap([0.24927783, 0.07516683, 0.25363684])